ading-product-lpf-griml
ESA-EarthCODE/open-science-catalog-metadata pull request #282
Opened 2024-11-08 09:01 UTC by open-science-data

Ading a product matadata to LPF GRIML project

2024-11-08 12:55 UTC, PennyHow requested changes

2024-11-08 12:55 UTC, PennyHow commented on products/esa-griml-iml-fv1/collection.json
> +    "description": "This ice marginal lake dataset is a series of annual inventories, mapping the extent and presence of lakes across Greenland that share a margin with the Greenland Ice Sheet and/or
The date in brackets at the end of this description does not need to be there. It is automatically generated by GEUS Dataverse. But I can understand keeping it if you would like this to follow exactly the description on the GEUS Dataverse.

2024-11-08 12:55 UTC, PennyHow commented on products/esa-griml-iml-fv1/collection.json
> +        "href": "https://doi.org/10.1038/s41598-021-83509-1",
This is a DOI reference to the 2021 paper presenting the previous Greenland inventory dataset. Can we update this once we have our new dataset paper published?

2024-11-08 12:55 UTC, PennyHow commented on products/esa-griml-iml-fv1/collection.json
> +      {
Suggestion: add Sentinel-2 reference here also, as Sentinel-2 is another key dataset used.

```suggestion
     {
        "rel": "related",
        "href": "../../eo-missions/sentinel-2/catalog.json",
        "type": "application/json",
        "title": "EO Mission: Sentinel-2"
      },

```

2024-11-08 12:55 UTC, PennyHow commented on products/esa-griml-iml-fv1/collection.json
> +    ],
Add Sentinel-2 here also.

```suggestion
    "sentinel-2"
    ],

```

2024-11-08 12:55 UTC, PennyHow commented on products/esa-griml-iml-fv1/collection.json
> +      "Land Surface Temperature"
```suggestion
      "Lake Surface Temperature"
```

2024-11-11 08:28 UTC, open-science-data commented on products/esa-griml-iml-fv1/collection.json
> +    "description": "This ice marginal lake dataset is a series of annual inventories, mapping the extent and presence of lakes across Greenland that share a margin with the Greenland Ice Sheet and/or
Ok, clear. Yes I copied paste the description from GEUS Daatverse. But of course it makes sense to remove this last date in the brackets.

2024-11-11 08:28 UTC, open-science-data commented on products/esa-griml-iml-fv1/collection.json
> +        "href": "https://doi.org/10.1038/s41598-021-83509-1",
Yes, since DOI is required to reference the dataset, I have just added a DOI to the dataset as I found I think in GEUS again. Of, course once the new DOI is assigned, we can update it to provide correct reference.

2024-11-11 08:29 UTC, open-science-data commented on products/esa-griml-iml-fv1/collection.json
> +      "Land Surface Temperature"
Typo here, thank you for spotting this.

2024-11-11 08:34 UTC, edobrowolska approved these changes

2024-11-11 08:34 UTC, merged